version: '3'
services:
  next:
    image: readme.so:latest
    container_name: readme.so
    restart: always
    ports:
      - '8057:3000'
    volumes:
      - ./data:/app/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
