services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    container_name: cup
    restart: unless-stopped
    command: serve
    ports:
      - 8061:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cup.json:/config/cup.json
