version: "3.8"

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    env_file: stack.env
    volumes:
      - ./code-server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    command: >
      /bin/bash -c " apt update && apt install -y python3 python3-pip python3-venv shellcheck docker-compose && /init"
    depends_on:
      - docker
    networks:
      - dev-net

  docker:
    image: docker:dind
    container_name: code-server-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    restart: unless-stopped
    networks:
      - dev-net

networks:
  dev-net:
