version: "3.8"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    env_file: stack.env
    volumes:
      - ./code-server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    depends_on:
      - docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - CUSTOM_INIT_SCRIPT=/config/custom-init.sh
    networks:
      - dev-net
  docker:
    image: docker:dind
    container_name: code-server-dind
    privileged: true
    ports:
      - "2375:2375"
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - ./dind/docker:/var/lib/docker
    restart: unless-stopped
    networks:
      - dev-net
networks:
  dev-net:
