services:
  teamspeak:
    image: teamspeak:latest
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    volumes:
      - ./data/teamspeak/data:/var/ts3server
    networks:
      - teamspeak-net
    depends_on:
      - db
    env_file:
      - stack.env
  db:
    image: mariadb:10.5
    restart: always
    ports:
      - 127.0.0.1:3366:3306
    volumes:
      - ./data/mariadb/data:/var/lib/mysql
    networks:
      - teamspeak-net
    env_file:
      - stack.env
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
networks:
  teamspeak-net:
