version: '3'
services:
  caddy:
    image: serfriz/caddy-cloudflare-ddns-security:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # For HTTP/3
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      DOMAIN: ${DOMAIN}
      POCKET_ID_CLIENT_ID: ${POCKET_ID_CLIENT_ID}
      POCKET_ID_CLIENT_SECRET: ${POCKET_ID_CLIENT_SECRET}
    volumes:
      - ./caddy:/etc/caddy
      - ./data:/data
      - ./config:/config

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-caddy
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - caddy

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy-caddy
    restart: unless-stopped
    command: --config /oauth2-proxy/oauth2-proxy.cfg
    ports:
      - 4180:4180
    environment:
      OAUTH_ID_CLIENT_ID: ${OAUTH_ID_CLIENT_ID}
      OAUTH_ID_CLIENT_SECRET: ${OAUTH_ID_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${OAUTH2_PROXY_OIDC_ISSUER_URL}
    volumes:
      - ./oauth2-proxy:/oauth2-proxy:ro
