services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    volumes:
      - mc-data:/data
    env_file:
      - stack.env
    environment:
      CF_API_KEY: ${CF_API_KEY}
volumes:
  mc-data:
