services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    volumes:
    - ./config:/config
    ports:
    - 9283:80
    restart: unless-stopped
    env_file:
    - stack.env
