version: "3.8"
services:
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - 8086:80
    volumes:
      - ./www/html/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/nginx.conf