version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      # WATCHTOWER_MONITOR_ONLY: "true"
      # WATCHTOWER_POLL_INTERVAL: "3600"
      WATCHTOWER_SCHEDULE: "0 0 8 * * *"
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
      WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_NOTIFICATION_URL}
    restart: unless-stopped
