version: '3'
services:
  opensearch-node1:
    restart: unless-stopped
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - opensearch-data1:/usr/share/opensearch/data
    ports:
    - 9210:9200
    - 9600:9600
    networks:
    - opensearch-net
    env_file:
    - stack.env
  opensearch-node2:
    restart: unless-stopped
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - opensearch-data2:/usr/share/opensearch/data
    networks:
    - opensearch-net
    env_file:
    - stack.env
  opensearch-dashboards:
    restart: unless-stopped
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
    - 5601:5601
    expose:
    - '5601'
    networks:
    - opensearch-net
    env_file:
    - stack.env
volumes:
  opensearch-data1: null
  opensearch-data2: null
networks:
  opensearch-net: null
