version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    container_name: valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - ./valheim-server/config:/config
      - ./valheim-server/data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
    env_file:
      - stack.env
    restart: unless-stopped
    stop_grace_period: 2m