version: '3.9'
services:
  palworld-dedicated-server:
    #build: .
    container_name: palworld-server
    image: jammsen/palworld-dedicated-server:latest
    restart: unless-stopped
    ports:
      - target: 8211 # Gamerserver port inside of the container
        published: 8211 # Gamerserver port on your host
        protocol: udp
        mode: host
      - target: 25575 # RCON port inside of the container
        published: 25575 # RCON port on your host
        protocol: tcp
        mode: host
    volumes:
      - ./game:/palworld
    env_file:
      - stack.env
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SERVER_PASSWORD: ${SERVER_PASSWORD}
