services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
    - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
    - stack.env
  chrome:
    image: ghcr.io/browserless/chromium:latest
    restart: unless-stopped
    extra_hosts:
    - host.docker.internal:host-gateway
    env_file:
    - stack.env
  app:
    image: amruthpillai/reactive-resume:latest
    restart: unless-stopped
    ports:
    - 3007:3000
    depends_on:
    - postgres
    - chrome
    env_file:
    - stack.env
volumes:
  postgres_data: null
