version: '3'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
    - 9000:9000
    - 9001:9001
    networks:
    - minionetwork
    volumes:
    - minio_data:/data
    command: server /data --console-address ":9001"
    env_file:
    - stack.env
networks:
  minionetwork:
    driver: bridge
volumes:
  minio_data:
    driver: local
