version: '3.7'
services:
  courier:
    container_name: courier
    image: tborychowski/courier
    restart: unless-stopped
    ports:
      - 8086:3000
    env_file:
      - stack.env
    environment:
      TOKEN: ${TOKEN}
