version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 192.168.1.100:53:53/tcp
      - 192.168.1.100:53:53/udp
      - 8053:80/tcp
    dns:
      - 127.0.0.1
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
      - ./var/log:/var/log
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      WEBPASSWORD: ${WEBPASSWORD}
