version: '3.3'
services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
    - 8055:8080
    volumes:
    - ./StirlingPDF/trainingData:/usr/share/tessdata
    - ./StirlingPDF/extraConfigs:/configs
    - ./StirlingPDF/customFiles:/customFiles/
    - ./StirlingPDF/logs:/logs/
    - ./StirlingPDF/pipeline:/pipeline/
    env_file:
    - stack.env
