services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    restart: unless-stopped
    ports:
      - 8062:80
    env_file:
      - stack.env
    environment:
      PUBLIC_APP_URL: ${PUBLIC_APP_URL}
      MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
    volumes:
      - "./data:/app/backend/data"
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
