version: '3'
services:
  2fauth:
    image: 2fauth/2fauth
    container_name: 2fauth
    volumes:
      - ./2fauth:/2fauth
    ports:
      - 8085:8000/tcp
    env_file:
      - stack.env
    environment:
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      SITE_OWNER: ${SITE_OWNER}
