services:
  fluentd-syslog:
    container_name: fluentd-syslog
    restart: unless-stopped
    image: fluentd-v2:latest
    tty: true
    ports:
    - 5000:5000/tcp
    - 5001:5001/udp
    volumes:
    - /etc/fluentd/syslog:/etc/fluentd/
  fluentd-http:
    container_name: fluentd-http
    restart: unless-stopped
    image: fluentd-v2:latest
    tty: true
    ports:
    - 5443:5443
    volumes:
    - /etc/fluentd/http:/etc/fluentd/
  fluentd-beats:
    container_name: fluentd-beats
    restart: unless-stopped
    image: fluentd-v2:latest
    tty: true
    ports:
    - 5002:5002/tcp
    volumes:
    - /etc/fluentd/beats:/etc/fluentd/
    env_file:
    - stack.env
