version: '3.8'
services:
  project-zomboid:
    container_name: projectzomboid-server
    image: pepecitron/projectzomboid-server
    restart: unless-stopped
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
    volumes:
      - ./data/server-file:/data/server-file
      - ./data/config:/data/config
    env_file:
      - stack.env
    environment:
      SERVER_ADMIN_PASSWORD: ${SERVER_ADMIN_PASSWORD}
      SERVER_PASSWORD: ${SERVER_PASSWORD}
